spring.application.name=sri_project
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.port=${PORT:8080}


server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.datasource.url=jdbc:mysql://localhost:3306/sri_stats_db?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=Ricris
spring.datasource.password=2341
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Correo (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=julcortezm.jys@gmail.com
spring.mail.password=egjlvqmmovkzqvhb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
